### ISSUE TITLE
Semantic Data Source Credentials

### ISSUE THREAD

**Issue by Dinnerticketboy** [jamf/powerbi#37]
Hi,
Great work with this.
I'm using a client id/secret to access my API (as we use SSO for authentication).  This works well while developing my reports.
What I'm having problem with is to schedule updates to the data via the online portal.
Only Basic credentials is available as an option for my Jamf Pro login details:

![PowerBI Semantic Creds](https://github.com/user-attachments/assets/1aabbd4e-3e13-4f3d-bc08-50fb29ffc3d0)

**Comment by jfretheim** [comment]
In order to use the pre-release version of the connector from the online portal, you'll need to use Microsoft's On-Premises Data Gateway to do so. There's a section in the middle of this discussion post headed "powerbi.com" with links and some details: https://github.com/jamf/powerbi/discussions/33

That said, the version currently on `develop` has been submitted to Microsoft and the certification review is complete. It is anticipated to be included in the mid-November release for Power BI Desktop and cloud services, so you may just want to wait until then. That release date can always change, but that's the best information we currently have.

Thank you for trying this out and letting us know, @Dinnerticketboy! Sorry for the delay in responding here—I thought I had my notifications all set up for this repo, but didn't see your note until I went to check on things today.

**Comment by jfretheim** [comment]
2.0.0 is now released for both Power BI Desktop and powerbi.com (see #39), so this issue should be resolved. Please re-open if you continue to run into it, and thanks again for reporting, @Dinnerticketboy.
